import discord
from . import utils as utils
from _typeshed import Incomplete
from discord.ext import commands

class Stuff(commands.Cog):
    async def on_message(self, message: discord.Message): ...
    bot: Incomplete
    def __init__(self, bot) -> None: ...
    owners: Incomplete
    async def find(self) -> None: ...
    @property
    def display_emoji(self): ...
    async def credits(self, ctx) -> None: ...
    async def ping(self, ctx) -> None: ...
    async def status(self, ctx) -> None: ...
    async def node_stats(self, ctx) -> None: ...

async def setup(bot) -> None: ...
